### ISSUE TITLE
Sending embed as Rejection

### ISSUE THREAD

**Issue by JamesHawkinss** [synzen/discord.js-prompts#3]
Hi there!

When throwing a Rejection from a PromptNode, it seems that I can only send a string as the message. Is it possible to send an embed? If so, how?

Thanks :D

**Comment by synzen** [comment]
Hi, it was previously not possible but I've now added support for it in https://github.com/synzen/discord.js-prompts/commit/092962cbe82421bb4d407960b5cc5ebecbeabd4f, available in v2.2.0. To use it, replace your thrown `Rejection` with a thrown `DiscordRejection` that's created like so:

```js
const Discord = require('discord.js')
const { DiscordRejection } = require('discord.js-prompts')

const embed = new Discord.MessageEmbed({
    description: 'My description'
})

new DiscordRejection('Error text', embed)
// If you don't want any text, just pass an empty string ""
```

 Thanks for the suggestion.
