### ISSUE TITLE
MenuEmbed suggestion/confusion

### ISSUE THREAD

**Issue by Syrup** [synzen/discord.js-prompts#9]
Hello, can you add an example of `MenuEmbed`?, because I don't understand the one in README.md

**Comment by synzen** [comment]
Hi, since that is an example already, what is it that you don't understand about it?

**Comment by Syrup** [comment]
Oh, I've been studying it for a week and now I get it. But can it only be `MenuEmbed` not with the prompt?

**Comment by synzen** [comment]
What do you mean not with prompt? Because it's essentially just a wrapper on discord.js's `MessageEmbed`, where it auto-handles pagination and adding options

**Comment by Syrup** [comment]
Yes, I just want to embed it not with the prompt

**Comment by synzen** [comment]
Unfortunately it's only meant for use with prompts. If you'd like to send an embed with pagination, you'll have to make an API using the methods on it https://github.com/synzen/discord.js-prompts/blob/master/src/MenuEmbed.ts.,

**Comment by Syrup** [comment]
Ok, thanks for helping
